version: '3.8'
services:
  backend:
    build: ./app/backend
    container_name: taskflow-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./app/frontend
    container_name: taskflow-frontend
    ports:
      - "8090:80"
    depends_on:
      - backend
    restart: unless-stopped
